<a href="https://colab.research.google.com/github/jyotinayak321/IBM-training_-learning-/blob/main/Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
1. creating array ->dimenstionarray ,-> indexing,-> slicing
2. shape & reshape (used in ml)
3. join,slipt,search,sort(DL in speciiaaly in tensorflow)

random ->
py.randam.rand()
np.random.randit()
np.random.choice()
np.random.shuffle()
np.random.permutation()

3.ufuncs ->np.add(),,np.subtrack(),np.log(),mp.exp(),,np.min(),np.max(),np.absolutes()

this libray is used for statistical and mathematical

In [ ]:
# numpyy is numerical python -libraies used for working with arrays

In [ ]:
#ndarray(as compare to list it exetutable speed is 10x to list)

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4]) # humko ndarray ko array() ka ander hi include kra ha
print(arr)  # o/p:<built-in function array>
#array o/p always in list

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# numpy is fast executable
# source code fo rnumpy is located at this github repository

#code repository:github
#digital repository :kaggle

In [ ]:
#Dimension in Arrays
#nested arrays - these are arrays that have arrays as their elements
# there is 0D,1D,2D,3D arrays
#0D arrays



In [ ]:
import numpy as np
arr = np.array([1]) #0-D array
print(arr)
print(arr.ndim)
print(arr.shape)

[1]
1
(1,)


In [ ]:
import numpy as np
arr = np.array([1,4,5]) #1-D array
print(arr)

[1 4 5]


In [ ]:
import numpy as np
arr = np.array([[1,2],[11,23]]) #2-D array
print(arr)

[[ 1  2]
 [11 23]]


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[2,4,5]])
print(arr)

[[1 2 3]
 [2 4 5]]


In [ ]:
import numpy as np
arr = np.array([[[2,2],[2,3],[4,4]],[[1,2],[2,3],[5,3]]]) #nested array  ,it is 3-D array in nested
print("the dimenstion of array is: ",arr.ndim)
print(arr)

the dimenstion of array is:  3
[[[2 2]
  [2 3]
  [4 4]]

 [[1 2]
  [2 3]
  [5 3]]]


ARRAY INDEXING

In [ ]:
# array indexing
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])  # indexing


1


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[1,2,3,4]])
print(arr[0])

# in 2D the  [2,4] 2 is dim and 4 is index
# in 3D   arr[block, row, column]

[1 2 3 4]


In [ ]:
arr = np.array([
    [[2,2,3],[2,3,5],[4,4,8]],
    [[1,2,2],[2,3,0],[5,3,3]],[[1,2,2],[2,3,0],[5,3,3]]
])
print(arr[0,1,2])
print(arr[1,1,2])
#print(arr.shape)

5
[[4 4 8]
 [5 3 3]]


In [ ]:
# in 2-D array [dimension,index]
#access element on th 1st rows ,2nd colm
arr =np.array([[2,2,3],[2,3,5]])
print(arr[0,2])

3


Slicing in array
[start:end]
[start,end]
[start:end:stop]

In [ ]:
arr =np.array([[2,2,3],[2,3,5],[2,3,3]])
print(arr[0:1])  # 2 is not include
print(" slicing of the  array is" ,arr[1:2])

arr = np.array([
    [[2,2,3],[2,3,5],[4,4,8]],
    [[1,2,2],[2,3,0],[5,3,3]],[[1,2,2],[2,3,0],[5,3,3]],[[1,2,2],[2,3,0],[5,3,3]]
])
print(arr[0:3:2])

print("next")

print(arr[0:2, 0:4, 0:4])


[[2 2 3]]
 slicing of the  array is [[2 3 5]]
[[[2 2 3]
  [2 3 5]
  [4 4 8]]

 [[1 2 2]
  [2 3 0]
  [5 3 3]]]
next
[[[2 2 3]
  [2 3 5]
  [4 4 8]]

 [[1 2 2]
  [2 3 0]
  [5 3 3]]]
[]


In [ ]:
arr =np.array([[2,2,3],[2,3,5]])
print(arr[:1])

[[2 2 3]]


In [ ]:
arr =np.array([[2,2,3],[2,3,5]])
print(arr.shape)
print(arr[1:])

(2, 3)
[[2 3 5]]


In [ ]:
arr = np.array([
    [2,2,3],
    [2,3,5],
    [2,3,5],
    [2,1,5],
    [2,3,5]
])

print(arr[0:3:2])

[[2 2 3]
 [2 3 5]]


In [ ]:
import numpy as np
a = np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[2,4,6]])
d= np.array([[[1,2,3],[2,3,4]],[[2,3,4],[3,6,7]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


In [ ]:
# use for high dimentional arrays  -- we define the no of dimention by using the atrribute ndmin
import numpy as np
arr = np.array([1,2,3,4,5] ,ndmin= 5)
print(arr)
print(arr[0:2,1:4]) # 0:2 is dim and 1:4 is indexing

[[[[[1 2 3 4 5]]]]]


# SHAPING and Reshaping (used in Ml)


1.   Shows the dimensions of an array
2.   Returns a tuple
3.   Does not modify the array



In [ ]:
#shaping of the array --shape of the array is the no of element  in each dimenstion(shapes o/p always in TUPLE)

# numpy have attributes called shape that returns a tuple a with each index having

# no of coorosponding elements
arr= np.array([[[1,2,3],[2,3,4]]])
print(arr.shape)
arr= np.array([[[1,2,3],[2,3,4]],[[2,3,4],[3,6,7]]])
print(arr.shape)  #

(1, 2, 3)
(2, 2, 3)


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[2,2,2,2,2]],ndmin = 5)
print(arr)                                     # 1 is  rows and 4 is element
print('shape of the array:',arr.shape)

[[[[[1 2 3 4 5]
    [2 2 2 2 2]]]]]
shape of the array: (1, 1, 1, 2, 5)


In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[2,2,2,2,2]],[[1,2,3,4,5],[2,2,2,2,2]]],ndmin = 5)
print(arr)                                     # 1 is  rows and 4 is element
print('shape of the array:',arr.shape)

[[[[[1 2 3 4 5]
    [2 2 2 2 2]]

   [[1 2 3 4 5]
    [2 2 2 2 2]]]]]
shape of the array: (1, 1, 2, 2, 5)


In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[2,2,2,2,2]],[[1,2,3,4,5],[2,2,2,2,2]]],ndmin = 5)
print(arr)                                     # 1 is  rows and 4 is element
print('shape of the array:',arr.shape)

In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[2,3,4]]],ndmin = 5)
print(arr)                                     # 1 is  rows and 4 is element
print('shape of the array:',arr.shape)

[[[[[1 2 3]
    [2 3 4]]]]]
shape of the array: (1, 1, 1, 2, 3)


## Reshaping


1.   Changes the dimensions of an array
2.   Returns a new array (unless assigned back or viewed)
3.   Rearranges the array into a new shape


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.reshape(2,6))  # (row,col)

print(arr.reshape(2,3,2))   #2block,3rows ,2colm

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Flattering :convert any array into 1-D array


In [ ]:
arr =np.array([[2,2,3],[2,3,5]])
print(arr.reshape(-1))


[2 2 3 2 3 5]


In [ ]:
arr = np.array([
    [[2,2,3],[2,3,5],[4,4,8]],
    [[1,2,2],[2,3,0],[5,3,3]],[[1,2,2],[2,3,0],[5,3,3]],[[1,2,2],[2,3,0],[5,3,3]]
])

print(arr.reshape(-1))

[2 2 3 2 3 5 4 4 8 1 2 2 2 3 0 5 3 3 1 2 2 2 3 0 5 3 3 1 2 2 2 3 0 5 3 3]


# Random module

In [ ]:
#Random modules to generate random number which are connot be predicted  logically

#ML we do prediction and hum machine ko prediction karna sikhate hai

from numpy import random

# to generate the randam value b/w 1 to 100

x = random.randint(100) #It returns a random integer between a and b inclusive

b = random.randint(2,5) # it provide the random value betwewen given values

x = random.randint(100,size=(5))  # it will provide the element of provided size in the array

g = random.randint(100,size=(3,5))  # it provide the randown values in 3 rows and 5 colm

h = random.rand(40)

print(h)    # rand() generate the 40 random element in float
print(g)
print(x)
print(b)
print(x)

[0.96838341 0.79276164 0.6942215  0.78392062 0.17216635 0.40795092
 0.1145193  0.31511839 0.10369357 0.31919136 0.09853204 0.37868433
 0.77429126 0.99824439 0.08374387 0.3253823  0.84035592 0.00538404
 0.56416315 0.03651812 0.12055229 0.64661987 0.02105111 0.21374632
 0.38671985 0.11145039 0.75190646 0.52184218 0.30738636 0.14295276
 0.56549881 0.05470336 0.03660533 0.08025088 0.32528219 0.76088169
 0.69267615 0.98636905 0.21282468 0.35473975]
[[76 69 78 65 28]
 [75 92 54  5 63]
 [45 49 47 50 58]]
[68 46 87 72 86]
4
[68 46 87 72 86]


# **random.choice():Ek sequence (list, tuple, string) se ek random element return karta hai**

In [ ]:
laptop = ["acer", "Hp","asus"]
x = random.choice(laptop)
print(x)

Hp


In [ ]:

x = random.choice([3,5,7,9],size=(3,5))  #
print(x)

[[7 5 3 3 3]
 [7 7 3 5 7]
 [7 5 9 5 9]]


# **Shuffle: yeh original array ko change kr deta ha**
**## permutation: yeh origianal  array ko chage nahi karta h**

In [ ]:
arr = np.array([1,2,3,4,5]) # shuffle (Koi new list return nahi karta)
random.shuffle(arr)
print(arr)

[5 2 1 3 4]


In [ ]:
# permutation
arr = np.array([1,2,3,4,5]) # Ye original array ki values ka ek naya shuffled array return karta hai.Isliye arr waise hi rehta hai.
random.permutation(arr)
print(arr)


[1 2 3 4 5]
