<a href="https://colab.research.google.com/github/jyotinayak321/IBM-training_-learning-/blob/main/Copy_of_numpy_02(ufuncs).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


**ufuncs ** *(universal function)*
vectoorization--process of converting iterative statement into vector -b

Vectorization means:

Converting an iterative (loop-based) operation into an array operation.

In [ ]:
x=[1,2,3,4]
y = [4,5,6,7]
z = np.add(x,y)
print(z)


[ 5  7  9 11]


Here:

myadd (first argument) → your Python function
2 → takes 2 inputs (x and y)
1 → returns 1 output

np.frompyfunc() converts your normal Python function into a NumPy ufunc.

In [ ]:

# create it own ufunc -- using frompfunc() method

def myadd(x,y):
  return x+y

myadd = np.frompyfunc(myadd,2,1)   # frompyfunc command is use to customize your own ufuncs
print(myadd(y,z))
print(myadd([1,2,3,4],[5,6,7,8]))

[9 12 15 18]
[6 8 10 12]


# **ufuncs operation add(),subtract(),multiply(),divide(),power(),mod(),radd(),**
# **subract(),divide(),multiply()**

In [ ]:
#add
arr1 = np.array([10,11,12,13,14])
arr2 = np.array([20,21,22,23,24])

newarr = np.add(arr1,arr2)
print(newarr)

[30 32 34 36 38]


In [ ]:
#subtract
arr1 = np.array([10,11,12,13,14])
arr2 = np.array([20,21,22,23,24])

newarr = np.subtract(arr1,arr2)
print(newarr)

[-10 -10 -10 -10 -10]


In [ ]:
#multiply
arr1 = np.array([10,11,12,13,14])
arr2 = np.array([20,21,22,23,24])

newarr = np.multiply(arr1,arr2)
print(newarr)

[200 231 264 299 336]


In [ ]:
#divide
arr1 = np.array([10,11,12,13,14])
arr2 = np.array([20,21,22,23,24])

newarr = np.divide(arr1,arr2)
print(newarr)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333]


In [ ]:
#power
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,2,2,2,2])

newarr = np.power(arr1,arr2)
print(newarr)

[ 1  4  9 16 25]


In [ ]:
#mod (the modulus operation)
arr1 = np.array([10,11,12,13,14])
arr2 = np.array([20,21,22,23,24])

newarr = np.mod(arr2,arr1)
print(newarr)

[ 0 10 10 10 10]


In [ ]:
#LOG
newarr = np.log(arr2)
print(newarr)
newarr = np.log(arr1)
print(newarr)

x=np.array([5])
newarr = np.log(x)
print(newarr)


[0.69314718 0.69314718 0.69314718 0.69314718 0.69314718]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.60943791]


In [ ]:
x=np.array([1,2,3])
exp_arr = np.exp(x)
print(exp_arr)


[ 2.71828183  7.3890561  20.08553692]


In [ ]:
# log of exponicial
#log(exp(x))
v = np.exp([1,2])
r = np.log(v)
print(r)

[1. 2.]


In [ ]:
#square root of
a = np.array([1,4,9,16,25])
b = np.sqrt(a)
print(b)

[1. 2. 3. 4. 5.]


In [ ]:
#minimum and maximum
a = np.array([1,4,9,16,25])

b = np.array([1,67,9,76,25])

print(np.maximum(a,b))
print(np.minimum(a,b))

[ 1 67  9 76 25]
[ 1  4  9 16 25]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
newarr = np.sum(arr1,arr2)
print(newarr)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
x=[1,2,3,4]
y = [4,5,6,7]
z = np.add(x,y)
print(z)

In [ ]:
#submition ,act like epsilon(it also work with along ans axis)
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([10,20,30,40,50,60])
newarr = np.sum([arr1,arr2])
print(newarr)

420


In [ ]:
#SUMMITION over axis
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([10,20,30,40,50,60])
newarr = np.sum([arr1,arr2],axis=1)
print(newarr)



[210 210]


# **cumulative summation--cumsum() **

In [ ]:
#cumulative summation--cumsum() it add the array element parsiarlyy

#  1,1+2,1+2+3,....
arr = np.array([1,2,3,4,5,6])
newarr = np.cumsum(arr)
print(newarr)



[ 1  3  6 10 15 21]


In [ ]:
#PRODUCT of the array  --> multiplying all the elements together
arr = np.array([1,2,3,4,5])
x = np.prod(arr)
print(x)

120


In [ ]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6]])
x = np.prod(arr)
print(x)

86400


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
x = np.prod([arr1,arr2])
print(x)

14400


In [ ]:
#discreate diffeerence
arr =np.array([10,20,30,40])
newarr = np.diff(arr)
print(newarr)

[10 10 10]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
newarr = np.diff([arr1,arr2])
print(newarr)

[[1 1 1 1]
 [1 1 1 1]]


# ***CONCATENATE FUNCTION - The np.concatenate() function is used to join two or more arrays into a single array***

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([42,52,62])
arr=np.concatenate((arr1,arr2))   # make sure used ( ) pranenthesis  brackets rather then [ ]
print(arr)


[ 1  2  3 42 52 62]


In [ ]:
# join the 2-D array along axis
arr1=np.array([[10,20,30],[4,5,6]])
arr2=np.array([[70,85,97],[10,11,12]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)


[[10 20 30 70 85 97]
 [ 4  5  6 10 11 12]]


In [ ]:
arr1=np.array([[10,20,30],[4,5,6]])
arr2=np.array([[70,85,97],[10,11,12]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[10 20 30]
 [ 4  5  6]
 [70 85 97]
 [10 11 12]]


**join array using function --it is same as concatenate the only difference that stacking is done along new axis**



In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


**type of stack**

1.   hstack() : it will concatenate along the rows
2.   vstack() : it will conactenate along the colm
3.   dstack() : it will concatenate along the deepth


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


**vstack**

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


**dstack**
predimension array

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


**Array split method** : it means breaking the array into multiiple



In [ ]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)   # arrat_split() use to spplit the array ,array we want to split by the no we want to split
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


if no of split inc array by byeefaultcate the

In [ ]:
newarr = np.array_split(arr,5)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
arr = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
newarr = np.array_split(arr,3)   # arrat_split() use to spplit the array ,array we want to split by the no we want to split
print(newarr)
print(newarr[0])

[array([[1, 2, 3, 4, 5, 6]]), array([[2, 3, 4, 5, 6, 7]]), array([], shape=(0, 6), dtype=int64)]
[[1 2 3 4 5 6]]


In [ ]:
# split the 2D array into 3 3-D array
arr = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
newarr = np.array_split(arr,4)   # arrat_split() use to spplit the array ,array we want to split by the no we want to split

print(newarr)

[array([[1, 2, 3, 4, 5, 6]]), array([[2, 3, 4, 5, 6, 7]]), array([], shape=(0, 6), dtype=int64), array([], shape=(0, 6), dtype=int64)]
[array([[1, 2, 3, 4, 5, 6]]), array([[2, 3, 4, 5, 6, 7]]), array([], shape=(0, 6), dtype=int64), array([], shape=(0, 6), dtype=int64)]


In [ ]:
# split the 2-D array having  3 element each into 3 2-D arrays
arr = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[2,3,4,5,6,7]])
newarr = np.array_split(arr,3)
print(newarr)


[array([[1, 2, 3, 4, 5, 6]]), array([[2, 3, 4, 5, 6, 7]]), array([[2, 3, 4, 5, 6, 7]])]


In [ ]:
arr = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[2,3,4,5,6,7],[3,4,5,6,7,8]])
newarr = np.array_split(arr,4)
print(newarr)

[array([[1, 2, 3, 4, 5, 6]]), array([[2, 3, 4, 5, 6, 7]]), array([[2, 3, 4, 5, 6, 7]]), array([[3, 4, 5, 6, 7, 8]])]


# **hsplit(),vsplit(),dsplit()**

In [ ]:
arr = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[2,3,4,5,6,7],[3,4,5,6,7,8]])
newarr = np.hsplit(arr,4)
print(newarr)


ValueError: array split does not result in an equal division

In [ ]:
# the indexes that get a match,to search a array we use where() function

arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1,2,3,3,4,5,4,4])
x = np.where((arr == 4) | (arr==3))
print(x)

(array([2, 3, 4, 6, 7]),)


In [ ]:
arr = np.array([10,14,93,41,8,7])
x = np.where(arr % 2==0) # even
m = np.where(arr%2==1)
print(m)
print(x)

(array([2, 3, 5]),)
(array([0, 1, 4]),)


In [ ]:
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


#SORT

sort array create a copy of the arrayleaving the original  array


In [ ]:
arr = np.array([3,2,0,11])
print(np.sort(arr))  # it create a copy of original array

[ 0  2  3 11]
