<a href="https://colab.research.google.com/github/jyotinayak321/IBM-training_-learning-/blob/main/ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [153]:
import numpy as np
import pandas as pd

In [154]:
df = pd.read_csv('customer.csv') # read the dataset

In [155]:
df.sample(5)  # It will give me the random data for the give the 5 sample

,age,gender,review,education,purchased
9,74,Male,Good,UG,Yes
6,18,Male,Good,School,No
19,97,Male,Poor,PG,Yes
14,15,Male,Poor,PG,Yes
31,22,Female,Poor,School,Yes


**Create Features (X) and Target (y)**

In [156]:
"""df = df.iloc[:,2:]#df.iloc[rows, columns]
y = df.iloc[:,-1]"""


#---------or--------
X = df[['review','education']]
y = df['purchased']


In [157]:
df.head()



,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


In [158]:
print(X.head())
print(y.head())

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG
0    No
1    No
2    No
3    No
4    No
Name: purchased, dtype: object


**Split the data**

In [159]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [160]:
#This line imports the OrdinalEncoder class from Scikit-learn's preprocessing module.
from sklearn.preprocessing import OrdinalEncoder

OrdinalEncoder is used to convert categorical (text) data into numerical values.

Machine learning algorithms cannot directly understand text like:

Small
Medium
Large

So we convert them into numbers

In [161]:
from sklearn.model_selection import train_test_split

# **Create Encoder**

In [162]:
oe = OrdinalEncoder(
    categories=[
        ['Poor','Average','Good'],  #specify categories Because these values have an order.
        ['School','UG','PG']
    ]
)

In [163]:
X_train


,review,education
12,Poor,School
4,Average,UG
37,Average,PG
8,Average,UG
3,Good,PG
6,Good,School
41,Good,PG
46,Poor,PG
47,Good,PG
15,Poor,UG


In [166]:
oe.fit(X_train) #fit() learns the categories from the training data

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [167]:
X_train = oe.transform(X_train)

In [168]:

X_test = oe.transform(X_test)

In [170]:
X_train  #will see the transformed data.

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [171]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [172]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [173]:
#It imports the LabelEncoder class from Scikit-learn's preprocessing module.
from sklearn.preprocessing import LabelEncoder

In [174]:
le = LabelEncoder()

In [175]:
le.fit(y_train)

LabelEncoder()

In [176]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [177]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [178]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])